// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDHUsgg_Q2vRjpY6kl325s01TxqVFexqRE',
    appId: '1:882036514451:web:46b965f2d92fe9032f7766',
    messagingSenderId: '882036514451',
    projectId: 'itempulse-e177c',
    authDomain: 'itempulse-e177c.firebaseapp.com',
    storageBucket: 'itempulse-e177c.firebasestorage.app',
    measurementId: 'G-GXVXCQ71LG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB6_rficoX0sVwg1-kCqcRs7y_Ul8VjpK4',
    appId: '1:882036514451:android:2d00ceb3097555b82f7766',
    messagingSenderId: '882036514451',
    projectId: 'itempulse-e177c',
    storageBucket: 'itempulse-e177c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBfSL0zTCLamThPrvuhQgWj1wTJxhvPMUE',
    appId: '1:882036514451:ios:94c71a223899bd802f7766',
    messagingSenderId: '882036514451',
    projectId: 'itempulse-e177c',
    storageBucket: 'itempulse-e177c.firebasestorage.app',
    iosBundleId: 'com.example.itemPulseApp',
  );
}
